import type { Course } from "./types";

export const CORRETOR: Course = {
  slug: "corretor-do-zero",
  title: "Corretor do zero: dos primeiros passos à primeira venda",
  thesis: "Um caminho prático para quem quer entrar no mercado imobiliário, entender como a profissão funciona e construir as bases para conquistar os primeiros clientes e realizar as primeiras negociações.",
  category: "Profissões",
  gestor: "vinicius-silva",
  difficulty: "Iniciante",
  commitment: "12 módulos · cerca de 30 min de prática cada",
  project: "Meu plano de 90 dias como corretor",
  outcomes: ["Meu ponto de partida", "Meu mercado inicial", "Minha primeira análise de imóvel", "Meu perfil de cliente", "Minha primeira base de contatos", "Meu mapa de relacionamentos", "Meu roteiro de qualificação", "Meu processo de visita", "Meu sistema de follow-up", "Meu playbook de objeções", "Meu sistema de indicações", "Meu plano de 90 dias como corretor"],
  tools: ["Mapa do mercado", "Lista das primeiras 50 conexões", "Checklist da visita", "Construtor de follow-up", "Simulador de objeções"],
  next: [
    { slug: "networking-do-zero", why: "Na corretagem, quase tudo começa por relacionamento. Aprenda mais sobre como construir e manter sua rede." },
    { slug: "vendas-da-conversa-ao-cliente", why: "Leve o que você praticou nas objeções para qualquer conversa de venda." },
    { slug: "ia-no-trabalho", why: "Organize follow-ups, anúncios e rotina com ajuda de IA, sem perder o toque humano." },
  ],
  modules: [
    {
      key: "c01", title: "A profissão de corretor na vida real", question: "O que um corretor realmente faz o dia inteiro?",
      blocks: [
        { type: "concept", title: "Onde o corretor cria valor",
          what: "O corretor conecta pessoas a imóveis: encontra imóveis e compradores, entende o que o cliente precisa, cria confiança, negocia, acompanha e ajuda a fechar. Anunciar é só uma pequena parte.",
          why: "Quem entra achando que o trabalho é mostrar imóvel se frustra. A maior parte do tempo vai para prospectar, conversar, estudar o mercado e fazer follow-up.",
          example: "Uma venda pode envolver semanas de conversa, várias visitas, ajustes de proposta e documentação antes de qualquer comissão. A comissão costuma ser um percentual do valor negociado, dividido entre as partes envolvidas (imobiliária, captador, vendedor), e só é paga quando o negócio acontece.",
          mistake: "Fazer contas de quanto vai ganhar antes de entender quanto tempo leva para construir uma carteira. No Brasil, exercer a profissão também exige registro no CRECI da sua região." },
        { type: "video", title: "A realidade de começar como corretor" },
        { type: "fields", key: "c01.partida", title: "Por que quero ser corretor?", fields: [
          { k: "atrai", l: "O que te atrai na profissão?", multiline: true },
          { k: "espera", l: "O que você espera dela?", multiline: true },
          { k: "tempo", l: "Quanto tempo pode dedicar?", options: ["Algumas horas por semana", "Meio período", "Tempo integral", "Ainda não sei"] },
          { k: "experiencia", l: "Que experiência anterior pode te ajudar?" },
          { k: "sabe", l: "O que você já sabe sobre o mercado imobiliário?", multiline: true }] },
      ],
      output: { key: "c01.partida", title: "Meu ponto de partida" },
      community: "O que te fez pensar em ser corretor? Conte seu ponto de partida.",
      next: "Aprender a observar um mercado antes de tentar vender.",
    },
    {
      key: "c02", title: "Entenda o mercado antes de tentar vender", question: "Que pedaço do mercado você vai conhecer melhor do que ninguém?",
      blocks: [
        { type: "concept", title: "Um mercado, não todos",
          what: "Mercado imobiliário é a combinação de localização, tipo de imóvel (apartamento, casa, comercial, terreno), faixa de preço, perfil de comprador e de vendedor, lançamentos de construtoras, revenda, locação e imóveis para investimento.",
          why: "Quem tenta atender tudo não vira referência em nada. Começar por um recorte deixa você mais rápido para responder e mais confiável para o cliente.",
          example: "Em vez de “vendo imóveis em São Paulo”, algo como “apartamentos de 2 quartos na revenda, entre R$400 e R$700 mil, na zona oeste, para quem compra o primeiro imóvel”.",
          mistake: "Escolher a região pelo preço mais alto, e não pela facilidade de visitar, estudar e frequentar o local." },
        { type: "video", title: "Como começar a entender uma região de verdade" },
        { type: "fields", key: "c02.mercado", title: "Mapa do meu mercado", fields: [
          { k: "regiao", l: "Região", ph: "Bairros ou cidade" },
          { k: "tipo", l: "Tipo de imóvel", options: ["Apartamento", "Casa", "Comercial", "Terreno", "Lançamentos", "Locação"] },
          { k: "faixa", l: "Faixa de preço", ph: "Ex.: R$300 a R$600 mil" },
          { k: "cliente", l: "Tipo de cliente", options: ["Primeiro imóvel", "Família", "Investidor", "Upgrade", "Downsize", "Mudança de cidade", "Locação"] },
          { k: "porque", l: "Por que esse recorte faz sentido para você?", multiline: true }] },
      ],
      output: { key: "c02.mercado", title: "Meu mercado inicial" },
      community: "Que região você escolheu e o que já percebeu de diferente nela?",
      next: "Conhecer a fundo o que você está vendendo.",
    },
    {
      key: "c03", title: "Conheça o que você está vendendo", question: "Para quem esse imóvel serve, e para quem não serve?",
      blocks: [
        { type: "concept", title: "Produto, preço e comparação",
          what: "Conhecer um imóvel é entender características, localização, preço, comparáveis da região, pontos fortes, pontos fracos e objeções prováveis. Também é saber, em linhas gerais, quais questões de documentação e financiamento vão surgir na negociação.",
          why: "O corretor que conhece o produto conversa diferente: responde com segurança, aponta alternativas e não promete o que o imóvel não entrega.",
          example: "Um apartamento sem vaga pode ser um problema para uma família e uma vantagem de preço para um estudante sem carro.",
          mistake: "Esconder pontos fracos. O cliente descobre na visita, e a confiança se perde. Dúvidas jurídicas ou documentais específicas devem ir para um profissional habilitado." },
        { type: "video", title: "O corretor que conhece o produto conversa diferente" },
        { type: "fields", key: "c03.analise", title: "Analise um imóvel", help: "Escolha um anúncio real da sua região e analise.", fields: [
          { k: "anuncio", l: "Qual imóvel? (link ou descrição)" },
          { k: "serve", l: "Para quem serve?", multiline: true },
          { k: "naoserve", l: "Para quem NÃO serve?", multiline: true },
          { k: "fortes", l: "Quais são os pontos fortes?", multiline: true },
          { k: "objecoes", l: "Quais são as objeções prováveis?", multiline: true },
          { k: "alternativas", l: "Que alternativas o comprador poderia considerar?", multiline: true }] },
      ],
      output: { key: "c03.analise", title: "Minha primeira análise de imóvel" },
      community: "Compartilhe um ponto fraco de imóvel que, para o cliente certo, virou vantagem.",
      next: "Entender quem é o seu cliente.",
    },
    {
      key: "c04", title: "Quem é o seu cliente?", question: "Por que essa pessoa quer comprar agora?",
      blocks: [
        { type: "concept", title: "Perfis diferentes, decisões diferentes",
          what: "Primeiro imóvel, família, investidor, upgrade, downsize, mudança de cidade e locação: cada perfil tem motivação, urgência, orçamento e medos diferentes.",
          why: "Quando você entende o perfil, para de mandar imóveis aleatórios e passa a sugerir o que faz sentido.",
          example: "Um investidor olha rentabilidade e liquidez. Uma família olha escola, segurança e espaço. O mesmo imóvel pede conversas opostas.",
          mistake: "Tratar todo cliente como alguém que “quer o melhor pelo menor preço”." },
        { type: "fields", key: "c04.cliente", title: "Meu primeiro perfil de cliente", fields: [
          { k: "perfil", l: "Perfil", options: ["Primeiro imóvel", "Família", "Investidor", "Upgrade", "Downsize", "Mudança de cidade", "Locação"] },
          { k: "procura", l: "O que procura?", multiline: true },
          { k: "agora", l: "Por que agora?" },
          { k: "orcamento", l: "Orçamento" },
          { k: "local", l: "Localização" },
          { k: "prioridades", l: "Prioridades", multiline: true },
          { k: "preocupacoes", l: "Preocupações", multiline: true },
          { k: "decisao", l: "Como decide? Quem participa da decisão?" }] },
      ],
      output: { key: "c04.cliente", title: "Meu cliente" },
      community: "Qual perfil de cliente você acha mais difícil de entender, e por quê?",
      next: "Montar a sua primeira base de contatos.",
    },
    {
      key: "c05", title: "Como conseguir os primeiros contatos", question: "De onde vão vir as suas primeiras conversas?",
      blocks: [
        { type: "concept", title: "Contatos não aparecem sozinhos",
          what: "Os primeiros contatos vêm da rede que você já tem, indicações, redes sociais, relações locais, eventos, portais, construtoras e imobiliárias, comunidade, conteúdo e prospecção ativa.",
          why: "Ninguém começa com clientes. Começa com conversas. Quanto mais fontes você testa com constância, mais rápido descobre o que funciona para você.",
          example: "Avisar 30 pessoas próximas que você começou na profissão, com uma mensagem clara sobre a região e o tipo de imóvel que atende, costuma gerar as primeiras indicações.",
          mistake: "Ficar esperando o portal ou a imobiliária mandar clientes prontos." },
        { type: "list", key: "c05.base", title: "Primeiras 50 conexões", max: 50, statusLabel: "Status", statuses: ["A contatar", "Contatado", "Conversamos", "Indicou alguém", "Sem interesse"],
          fields: [{ k: "nome", l: "Nome" }, { k: "relacao", l: "Relação", ph: "Amigo, ex-colega, vizinho…" }, { k: "necessidade", l: "Possível necessidade" }, { k: "indicacao", l: "Pode me apresentar a quem?" }, { k: "acao", l: "Próxima ação" }] },
      ],
      output: { key: "c05.base", title: "Minha primeira base" },
      community: "Qual fonte de contatos funcionou melhor para você até agora?",
      next: "Construir a rede de relações em volta da sua profissão.",
    },
    {
      key: "c06", title: "Networking para corretores", question: "Quem, além do cliente, faz um negócio acontecer?",
      blocks: [
        { type: "concept", title: "O ecossistema do corretor",
          what: "Um negócio imobiliário envolve muita gente: correspondentes bancários e profissionais de crédito, construtoras, outros corretores, advogados e despachantes, síndicos e porteiros, clientes antigos, comércio e comunidade local.",
          why: "Reputação e apresentações circulam nesse ecossistema. Quem é lembrado por ele recebe indicações e resolve problemas mais rápido.",
          example: "Um correspondente bancário que confia em você indica clientes já aprovados para financiamento.",
          mistake: "Ver outros corretores só como concorrentes. Muitas vendas acontecem em parceria." },
        { type: "video", title: "Relacionamentos no mercado imobiliário" },
        { type: "groups", key: "c06.ecossistema", title: "Meu ecossistema", help: "Adicione nomes ou iniciais. Só você vê.", ph: "Nome", groups: ["Crédito e financiamento", "Construtoras", "Outros corretores", "Advogados e despachantes", "Clientes antigos", "Comunidade local", "Pessoas que quero conhecer"] },
      ],
      output: { key: "c06.ecossistema", title: "Meu mapa de relacionamentos" },
      community: "Que parceria fora do óbvio já te ajudou a fechar ou destravar um negócio?",
      next: "Conduzir o primeiro atendimento.",
    },
    {
      key: "c07", title: "O primeiro atendimento", question: "O que perguntar antes de mandar qualquer imóvel?",
      blocks: [
        { type: "question", key: "c07.antes", prompt: "O cliente diz: “Estou procurando um apartamento de até R$700 mil.” O que você perguntaria em seguida?" },
        { type: "concept", title: "Qualificar antes de oferecer",
          what: "Um bom atendimento busca entender motivação, prazo, orçamento real, localização, o que é indispensável, o que é negociável, quem decide e se o financiamento está encaminhado.",
          why: "Mandar 20 imóveis sem entender o cliente gasta o tempo dos dois e passa a impressão de que você não escutou.",
          example: "“O que te fez começar a procurar agora? Esse valor já considera financiamento? O que não pode faltar de jeito nenhum? Quem mais vai participar da decisão?”",
          mistake: "Responder com uma lista de links logo na primeira mensagem." },
        { type: "question", key: "c07.depois", prompt: "Reescreva suas perguntas usando o roteiro: motivação, prazo, orçamento, local, indispensáveis, trocas aceitáveis, quem decide e financiamento." },
        { type: "compare", before: "c07.antes", after: "c07.depois", title: "Antes e depois" },
      ],
      output: { key: "c07.depois", title: "Meu roteiro de qualificação" },
      community: "Qual pergunta de atendimento mais te ajudou a entender um cliente?",
      next: "Preparar e conduzir uma visita.",
    },
    {
      key: "c08", title: "A visita", question: "Como conduzir uma visita sem virar apresentador de imóvel?",
      blocks: [
        { type: "concept", title: "Antes, durante e depois",
          what: "Antes: conheça o imóvel e o cliente, prepare perguntas e tenha alternativas. Durante: observe reações, pergunte, escute e explique com honestidade. Depois: colete a opinião, entenda objeções e combine o próximo passo.",
          why: "A visita é o momento em que o cliente mostra o que realmente importa, muitas vezes sem dizer.",
          example: "O cliente passa direto pela sala e fica cinco minutos na cozinha. Isso diz mais sobre as prioridades dele do que a ficha de atendimento.",
          mistake: "Falar o tempo todo e pressionar por uma decisão na hora." },
        { type: "video", title: "Como conduzir uma visita sem virar um apresentador de imóvel" },
        { type: "choices", key: "c08.checklist", multi: true, prompt: "Checklist da visita: marque o que você vai fazer sempre.", options: [
          "Revisar a ficha e os pontos fracos do imóvel", "Relembrar prioridades e medos do cliente", "Preparar 3 perguntas para fazer no local", "Ter 1 ou 2 alternativas em mente",
          "Observar onde o cliente para e o que ignora", "Perguntar mais do que apresentar", "Ser honesto sobre o que não é ideal", "Não pressionar por decisão na hora",
          "Pedir a opinião ao final", "Anotar objeções", "Combinar um próximo passo com data"] },
        { type: "fields", key: "c08.processo", title: "Meu processo de visita", fields: [
          { k: "antes", l: "O que faço antes?", multiline: true }, { k: "durante", l: "O que faço durante?", multiline: true }, { k: "depois", l: "O que faço depois?", multiline: true }] },
      ],
      output: { key: "c08.processo", title: "Meu processo de visita" },
      community: "O que você aprendeu sobre um cliente observando a visita, e não pelo que ele disse?",
      next: "Montar um sistema de follow-up.",
    },
    {
      key: "c09", title: "Follow-up", question: "Por que tantas oportunidades se perdem depois da primeira conversa?",
      blocks: [
        { type: "concept", title: "A venda costuma estar no retorno",
          what: "Follow-up é voltar a falar com o cliente no momento certo, com algo útil: um resumo, uma alternativa, uma resposta, uma novidade da região.",
          why: "A compra de um imóvel é uma decisão que leva tempo. Quem some na segunda semana perde o cliente para quem continuou presente com respeito.",
          example: "Depois da visita: “Obrigado pelo tempo hoje. Anotei que a cozinha pequena pesou. Separei duas opções com cozinha maior na mesma rua. Quer que eu mande?”",
          mistake: "Mandar só “E aí, alguma novidade?”." },
        { type: "fields", key: "c09.followup", title: "Construtor de follow-up", help: "Escreva a mensagem que você mandaria em cada momento.", fields: [
          { k: "contato", l: "Depois do primeiro contato", multiline: true },
          { k: "conversa", l: "Depois da conversa de atendimento", multiline: true },
          { k: "visita", l: "Depois da visita", multiline: true },
          { k: "proposta", l: "Depois da proposta", multiline: true },
          { k: "longo", l: "Acompanhamento de longo prazo (cliente que adiou)", multiline: true }] },
      ],
      output: { key: "c09.followup", title: "Meu sistema de follow-up" },
      community: "Compartilhe uma mensagem de follow-up que gerou resposta.",
      next: "Praticar negociação e objeções.",
    },
    {
      key: "c10", title: "Negociação e objeções", question: "O que está por trás de “está caro”?",
      blocks: [
        { type: "question", key: "c10.antes", prompt: "O cliente diz: “Está caro.” Escreva como você responderia hoje." },
        { type: "concept", title: "Objeção é informação",
          what: "Uma objeção mostra uma dúvida ainda não esclarecida, um medo ainda não superado ou uma prioridade ainda não atendida. O papel do corretor é entender, não rebater.",
          why: "Quem discute com a objeção perde a confiança. Quem pergunta descobre o que realmente impede a decisão.",
          example: "“Está caro comparado a quê? É o valor total ou a parcela que preocupa?” muda a conversa de preço para decisão.",
          mistake: "Baixar o preço ou insistir antes de entender o motivo." },
        { type: "scenarios", key: "c10.objecoes", title: "Simulador de objeções", intro: "Responda a cada objeção usando o roteiro.",
          items: ["Está caro.", "Vou pensar.", "Quero ver outros imóveis.", "Não gostei da localização.", "Vou esperar os juros baixarem.", "Preciso falar com meu parceiro."],
          framework: ["Valide sem concordar: “Faz sentido querer…”.", "Pergunte o que está por trás.", "Reconecte a conversa às prioridades que o cliente compartilhou.", "Proponha um próximo passo concreto e sem pressão."] },
        { type: "compare", before: "c10.antes", after: "c10.objecoes", title: "Antes e depois" },
      ],
      output: { key: "c10.objecoes", title: "Meu playbook de objeções" },
      community: "Qual objeção você mais escuta, e como tem respondido?",
      next: "Transformar cada negócio em reputação e indicações.",
    },
    {
      key: "c11", title: "Reputação e indicações", question: "O que acontece com o cliente depois da assinatura?",
      blocks: [
        { type: "concept", title: "O negócio não é o fim da relação",
          what: "Contato depois da venda, pedido de indicação no momento certo, avaliações, reputação local, conteúdo e rede profissional fazem cada cliente atendido gerar os próximos.",
          why: "Um cliente bem atendido conhece outras pessoas comprando, vendendo ou alugando. Indicação costuma chegar com mais confiança do que qualquer anúncio.",
          example: "Mandar uma mensagem no primeiro mês na casa nova e no aniversário da compra. Simples, e quase ninguém faz.",
          mistake: "Sumir depois da comissão e pedir indicação só quando precisa." },
        { type: "fields", key: "c11.indicacoes", title: "Meu sistema de indicações", fields: [
          { k: "pos", l: "Como vou manter contato depois da venda?", multiline: true },
          { k: "quando", l: "Em que momento vou pedir indicação, e como?", multiline: true },
          { k: "avaliacao", l: "Onde e como vou pedir avaliações?" },
          { k: "conteudo", l: "Que conteúdo posso compartilhar sobre minha região?", multiline: true },
          { k: "rede", l: "Quem da minha rede profissional vou manter por perto?" }] },
      ],
      output: { key: "c11.indicacoes", title: "Meu sistema de indicações" },
      community: "Como você mantém contato com clientes depois que o negócio acontece?",
      next: "Juntar tudo no seu plano de 90 dias.",
    },
    {
      key: "c12", title: "Os primeiros 90 dias", question: "O que você vai fazer, semana a semana, nos próximos três meses?",
      blocks: [
        { type: "concept", title: "Meça atividade, não só resultado",
          what: "Nos primeiros meses, o resultado financeiro depende de muita coisa fora do seu controle. As atividades, não: novos contatos, conversas, clientes qualificados, follow-ups, visitas, propostas e indicações.",
          why: "Acompanhar atividade mostra cedo o que está funcionando e evita desistir antes de a carteira amadurecer.",
          example: "Mês 1: aprender o mercado, construir a base, conhecer produto, criar rotina. Mês 2: prospectar, conversar, visitar, fazer follow-up. Mês 3: melhorar conversão, fortalecer relações, analisar resultados e ajustar.",
          mistake: "Definir só uma meta de faturamento e não saber o que fazer na segunda-feira." },
        { type: "video", title: "O que eu faria nos meus primeiros 90 dias se estivesse começando hoje" },
        { type: "fields", key: "c12.plano", title: "Meu plano de 90 dias", fields: [
          { k: "mes1", l: "Mês 1: aprender mercado, construir base, conhecer produto, criar rotina", multiline: true },
          { k: "mes2", l: "Mês 2: prospectar, conversar, visitar, fazer follow-up", multiline: true },
          { k: "mes3", l: "Mês 3: melhorar conversão, fortalecer relações, analisar e ajustar", multiline: true },
          { k: "rotina", l: "Minha rotina semanal de prospecção", multiline: true }] },
        { type: "fields", key: "c12.metas", title: "Minhas metas de atividade por semana", fields: [
          { k: "contatos", l: "Novos contatos" }, { k: "conversas", l: "Conversas" }, { k: "qualificados", l: "Clientes qualificados" },
          { k: "followups", l: "Follow-ups" }, { k: "visitas", l: "Visitas" }, { k: "propostas", l: "Propostas" }, { k: "indicacoes", l: "Indicações" },
          { k: "revisao", l: "Revisão semanal: o que vou olhar toda sexta-feira?", multiline: true }] },
      ],
      output: { key: "c12.plano", title: "Meu plano de 90 dias como corretor" },
      community: "Qual vai ser a sua meta de atividade da primeira semana?",
      next: "Revisar seu plano completo no seu espaço.",
    },
  ],
  finalPlan: {
    title: "Meu plano de 90 dias como corretor",
    sections: [
      { t: "Meu ponto de partida", keys: ["c01.partida"] }, { t: "Meu mercado", keys: ["c02.mercado"] },
      { t: "Meu conhecimento de produto", keys: ["c03.analise"] }, { t: "Meu cliente", keys: ["c04.cliente"] },
      { t: "Minha lista inicial de contatos", keys: ["c05.base"] }, { t: "Meu plano de networking", keys: ["c06.ecossistema"] },
      { t: "Meu roteiro de atendimento", keys: ["c07.depois"] }, { t: "Meu roteiro de visita", keys: ["c08.checklist", "c08.processo"] },
      { t: "Meu sistema de follow-up", keys: ["c09.followup"] }, { t: "Meu playbook de objeções", keys: ["c10.objecoes"] },
      { t: "Meu sistema de indicações", keys: ["c11.indicacoes"] }, { t: "Minhas metas de atividade", keys: ["c12.metas"] },
      { t: "Meu plano de 90 dias", keys: ["c12.plano"] },
    ],
  },
};
