import type { Course } from "./types";

export const DA_IDEIA: Course = {
  slug: "da-ideia-aos-primeiros-clientes",
  title: "Da ideia aos primeiros clientes",
  thesis: "Transforme uma ideia em hipóteses que podem ser testadas antes de comprometer tempo e dinheiro demais.",
  category: "Negócios",
  gestor: "eduardo-araujo",
  difficulty: "Fundamentos",
  commitment: "10 módulos · cerca de 40 min de prática cada",
  project: "Meu negócio",
  outcomes: ["Uma hipótese clara", "Um cliente definido", "Evidências organizadas", "A economia do negócio", "Uma primeira oferta", "Um experimento de 7 dias", "Uma lista de 20 pessoas", "Um script de conversa", "Uma decisão com base em dados", "Um plano de 30 dias"],
  tools: ["Validador de ideias", "Calculadora de viabilidade", "Plano de validação"],
  next: [
    { slug: "vendas-da-conversa-ao-cliente", why: "Você agora tem uma oferta. O próximo passo é aprender a conversar com quem pode comprá-la." },
    { slug: "networking-do-zero", why: "As primeiras vendas quase sempre passam por pessoas que você já conhece ou pode conhecer." },
  ],
  modules: [
    {
      key: "m01", title: "Sua ideia é uma hipótese", question: "O que você sabe de verdade e em que só acredita?",
      blocks: [
        { type: "question", key: "m01.antes", prompt: "Descreva sua ideia em uma frase, do jeito que você contaria para um amigo." },
        { type: "concept", title: "Ideia, hipótese e evidência",
          what: "Uma ideia é algo que você imagina. Uma hipótese é a ideia escrita de forma que possa estar errada: quem compra, qual problema, por que pagaria. Evidência é o que aconteceu no mundo real e confirma ou derruba a hipótese.",
          why: "Quase todo negócio que fracassa cedo começa tratando ideia como fato. Quando você escreve em forma de hipótese, sabe exatamente o que testar e para de gastar energia defendendo a ideia.",
          example: "Ideia: “um app para donos de pet”. Hipótese: “donos de cachorro que trabalham fora mais de 9 horas pagariam R$40 por um passeio no meio do dia”. Evidência: 6 de 15 vizinhos abordados aceitaram pagar uma semana adiantada.",
          mistake: "Contar a ideia para amigos, ouvir “que legal” e considerar isso validação. Elogio não custa nada. Evidência envolve alguém abrindo mão de tempo, dinheiro ou reputação." },
        { type: "video", title: "A ideia não importa tanto quanto você pensa" },
        { type: "fields", key: "m01.hipotese", title: "Minha hipótese", help: "Responda de forma específica. “Todo mundo” e “muita gente” não contam.", fields: [
          { k: "quem", l: "Quem compra?", ph: "Ex.: donos de cachorro que trabalham fora" },
          { k: "problema", l: "Qual problema existe?", ph: "Ex.: o cachorro fica sozinho 10 horas" },
          { k: "porque", l: "Por que alguém pagaria?", ph: "Ex.: culpa, bagunça em casa, saúde do animal" },
          { k: "agora", l: "Por que agora?", ph: "Ex.: voltaram ao escritório depois do home office" }] },
        { type: "compare", before: "m01.antes", after: "m01.hipotese", title: "Antes e depois" },
      ],
      output: { key: "m01.hipotese", title: "Minha hipótese" },
      community: "Qual hipótese sobre seu negócio você percebeu que estava tratando como fato?",
      next: "Descrever quem, de verdade, compraria.",
    },
    {
      key: "m02", title: "Quem realmente compraria?", question: "Você consegue descrever seu primeiro cliente sem dizer “todo mundo”?",
      blocks: [
        { type: "concept", title: "Cliente não é público-alvo",
          what: "Seu primeiro cliente é uma pessoa (ou empresa) específica que tem o problema, sente esse problema com frequência e tem como pagar pela solução.",
          why: "Quanto mais específico o cliente, mais fácil encontrá-lo, falar a língua dele e saber se a oferta faz sentido. “Mulheres de 25 a 40 anos” não diz onde encontrar ninguém.",
          example: "Em vez de “pequenas empresas”, escreva “donos de oficina mecânica com 2 a 5 funcionários, que ainda fazem orçamento no papel”. Agora você sabe onde procurar e o que perguntar.",
          mistake: "Confundir quem usa com quem decide. Numa escola, quem usa é o aluno, mas quem decide e paga pode ser a coordenação ou os pais." },
        { type: "video", title: "Seu cliente provavelmente não é quem você imagina" },
        { type: "fields", key: "m02.cliente", title: "Meu primeiro cliente", fields: [
          { k: "tipo", l: "Pessoa ou empresa?", options: ["Pessoa", "Empresa"] },
          { k: "onde", l: "Onde está?", ph: "Bairro, grupo, rede social, evento, setor" },
          { k: "problema", l: "Qual problema enfrenta?" },
          { k: "hoje", l: "Como resolve hoje?", ph: "Toda solução atual, mesmo improvisada, é sua concorrente" },
          { k: "decide", l: "Quem decide a compra?" },
          { k: "importancia", l: "Quanto esse problema importa?", options: ["Incômodo leve", "Atrapalha toda semana", "Custa dinheiro", "É urgente"] }] },
      ],
      output: { key: "m02.cliente", title: "Meu primeiro cliente" },
      community: "Quem você imaginava que seria seu cliente e quem descobriu que realmente é?",
      next: "Separar o que você observou do que está imaginando.",
    },
    {
      key: "m03", title: "Problema ou invenção?", question: "Que evidência você tem de que esse problema existe?",
      blocks: [
        { type: "concept", title: "Observação, opinião, sinal e evidência",
          what: "Observação é o que você viu. Opinião é o que alguém acha. Sinal é um comportamento que sugere interesse. Evidência é um comportamento que custou algo para a pessoa: pagou, se comprometeu, indicou alguém.",
          why: "Cada tipo pesa diferente. Dez opiniões positivas valem menos que uma pessoa que pagou adiantado.",
          example: "“Meus amigos acham ótimo” é opinião. “40 pessoas entraram na lista de espera” é sinal. “8 pessoas pagaram um sinal de R$20” é evidência.",
          mistake: "Usar pesquisa online (“o mercado de pets cresce 10% ao ano”) como prova de que as pessoas vão comprar de você." },
        { type: "classify", key: "m03.classificacao", prompt: "Classifique cada frase:", categories: ["Observação", "Opinião", "Sinal", "Evidência"], items: [
          { t: "Meu primo disse que usaria com certeza.", a: "Opinião", why: "Não custou nada para ele dizer isso." },
          { t: "Vi três vizinhos reclamando do mesmo problema no grupo do prédio.", a: "Observação" },
          { t: "25 pessoas deixaram e-mail numa página de interesse.", a: "Sinal", why: "Mostra interesse, mas ainda não compromisso." },
          { t: "Duas empresas pagaram metade antes de eu entregar.", a: "Evidência" },
          { t: "Num post, 60 pessoas curtiram a ideia.", a: "Sinal", why: "Curtir é barato; trate como pista, não prova." },
          { t: "Um cliente pediu para eu fazer de novo no mês que vem.", a: "Evidência" }] },
        { type: "video", title: "Como descobrir se existe demanda antes de gastar dinheiro" },
        { type: "tool", tool: "validador", key: "m03.validador", intro: "Use o Validador de ideias e registre aqui o que ele apontou." },
        { type: "fields", key: "m03.evidencias", title: "Minhas evidências", fields: [
          { k: "tenho", l: "Evidências que já tenho", multiline: true },
          { k: "sinais", l: "Sinais (interesse sem compromisso)", multiline: true },
          { k: "suposicao", l: "Maior suposição que ainda precisa ser provada" }] },
      ],
      output: { key: "m03.evidencias", title: "Minhas evidências" },
      community: "Qual é a hipótese mais difícil de provar no seu negócio?",
      next: "Ver se a conta fecha antes de investir.",
    },
    {
      key: "m04", title: "A matemática precisa fechar", question: "De quantas vendas você precisa para valer a pena?",
      blocks: [
        { type: "concept", title: "Receita, margem, CAC e ponto de equilíbrio",
          what: "Receita é o que entra. Custo variável é o que sai a cada venda. Margem é a diferença. CAC é quanto custa conquistar um cliente. Custos fixos existem mesmo sem vender. Ponto de equilíbrio é o número de vendas que paga tudo isso.",
          why: "Muita ideia boa morre porque cada venda dá prejuízo, ou porque são necessárias mais vendas do que é possível fazer.",
          example: "Bolo a R$60, ingredientes e embalagem R$25, entrega R$10: margem de R$25. Com R$1.000 de custos fixos por mês, são 40 bolos só para empatar, antes de você ganhar qualquer coisa.",
          mistake: "Esquecer o próprio tempo e o CAC. Se você gasta R$30 em anúncio para vender um bolo com R$25 de margem, cada venda custa dinheiro." },
        { type: "video", title: "Uma boa ideia com matemática ruim continua sendo um negócio ruim" },
        { type: "tool", tool: "viabilidade", key: "m04.economia", intro: "Ajuste os números do seu negócio. Use estimativas honestas; você pode voltar e corrigir." },
      ],
      output: { key: "m04.economia", title: "A economia do meu negócio" },
      community: "Qual número da calculadora mais te surpreendeu?",
      next: "Montar a oferta antes de construir o produto.",
    },
    {
      key: "m05", title: "Construa a oferta", question: "O que exatamente alguém está comprando?",
      blocks: [
        { type: "concept", title: "Produto não é oferta",
          what: "Produto é o que você entrega. Oferta é o pacote completo: para quem, qual resultado, como, por quanto, com que garantia e por que agora.",
          why: "As pessoas não compram o produto; compram a mudança que ele traz. A mesma aula pode não vender como “curso de Excel” e vender como “feche o mês da sua loja em 1 hora”.",
          example: "Produto: consultoria de redes sociais. Oferta: “para salões de beleza do bairro: 4 semanas para encher a agenda de terça e quarta, R$600, com 12 posts prontos e acompanhamento por WhatsApp”.",
          mistake: "Passar meses aperfeiçoando o produto sem nunca escrever a oferta e mostrar para alguém." },
        { type: "video", title: "Por que algumas coisas vendem e outras não" },
        { type: "fields", key: "m05.oferta", title: "Minha primeira oferta", fields: [
          { k: "para", l: "Para quem?" }, { k: "problema", l: "Qual problema?" },
          { k: "entrega", l: "O que entrego?", multiline: true }, { k: "resultado", l: "Qual resultado?" },
          { k: "preco", l: "Quanto custa?" }, { k: "agora", l: "Por que comprar agora?" },
          { k: "objecao", l: "Qual a principal objeção?" }] },
      ],
      output: { key: "m05.oferta", title: "Minha primeira oferta" },
      community: "Leia sua oferta em voz alta. O que soou estranho?",
      next: "Descobrir do jeito mais barato se você está errado.",
    },
    {
      key: "m06", title: "Teste antes de construir", question: "O que precisaria acontecer para essa ideia merecer mais investimento?",
      blocks: [
        { type: "concept", title: "Validação é tentar provar que você está errado",
          what: "Um experimento de validação é um teste pequeno, com prazo e uma meta numérica definida antes de começar.",
          why: "Definir o número antes impede que você reinterprete qualquer resultado como positivo. E testes pequenos fazem o erro custar pouco.",
          example: "“Em 7 dias, vou apresentar a oferta a 30 donos de salão. Se 3 pagarem o sinal, continuo. Se nenhum pagar, ajusto a oferta.”",
          mistake: "Construir o site, a marca e o produto inteiro antes de qualquer pessoa ter aceitado pagar." },
        { type: "video", title: "Como perder R$500 em vez de R$50.000 quando uma ideia estiver errada" },
        { type: "question", key: "m06.criterio", prompt: "O que precisaria acontecer para essa ideia merecer mais investimento?" },
        { type: "tool", tool: "plano", key: "m06.teste", intro: "Monte seu teste de 7 dias no Plano de validação e registre aqui o que vai medir." },
      ],
      output: { key: "m06.teste", title: "Meu experimento" },
      community: "Qual número vai te dizer que o teste deu certo?",
      next: "Listar as primeiras 20 pessoas a quem apresentar a oferta.",
    },
    {
      key: "m07", title: "As primeiras 20 pessoas", question: "Para quem você vai apresentar a oferta primeiro?",
      blocks: [
        { type: "concept", title: "Prospectar é escolher, não sair atirando",
          what: "Prospects são pessoas específicas, com nome, que provavelmente têm o problema e que você consegue alcançar.",
          why: "20 nomes reais ensinam mais que um anúncio para 20 mil desconhecidos. Você conversa, ouve objeções e ajusta rápido.",
          example: "Para um serviço de contabilidade para MEIs: 5 ex-colegas que abriram empresa, 6 pessoas de um grupo de empreendedores do bairro, 9 perfis que reclamaram de imposto num fórum.",
          mistake: "Achar que não conhece ninguém. Comece pelo seu círculo e peça indicações. Se não encontrar 20 pessoas, isso também é informação." },
        { type: "video", title: "Se você não consegue encontrar 20 pessoas, pare antes de procurar 20 mil" },
        { type: "list", key: "m07.prospects", title: "Minha primeira lista", max: 20, statusLabel: "Status",
          statuses: ["Identificado", "Contactado", "Respondeu", "Conversando", "Oferta apresentada", "Comprou", "Não interessado"],
          fields: [{ k: "nome", l: "Nome" }, { k: "empresa", l: "Empresa" }, { k: "motivo", l: "Motivo" }, { k: "canal", l: "Canal" }, { k: "notas", l: "Notas" }] },
      ],
      output: { key: "m07.prospects", title: "Minha primeira lista" },
      community: "Qual canal está funcionando melhor para chegar às pessoas?",
      next: "Praticar a conversa de venda.",
    },
    {
      key: "m08", title: "A primeira conversa de vendas", question: "O que você responde quando dizem que está caro?",
      blocks: [
        { type: "question", key: "m08.antes", prompt: "O cliente diz: “Está caro.” Escreva como você responderia hoje." },
        { type: "concept", title: "Venda é diagnóstico antes de persuasão",
          what: "Uma boa conversa segue: pergunta → problema → contexto → valor → oferta → objeção → próximo passo. Você fala menos do que ouve.",
          why: "Objeções quase sempre aparecem quando você apresenta a oferta antes de entender o problema. “Está caro” costuma significar “não ficou claro quanto isso vale para mim”.",
          example: "Em vez de dar desconto: “Faz sentido. Caro comparado a quê? … Você comentou que perde duas clientes por semana por falta de horário. Quanto isso representa no mês?”",
          mistake: "Responder à objeção na defensiva ou baixar o preço na primeira resistência." },
        { type: "video", title: "Venda é diagnóstico antes de persuasão" },
        { type: "scenarios", key: "m08.script", intro: "Agora responda de novo usando o roteiro e pratique as respostas às outras objeções.",
          items: ["Está caro.", "Preciso pensar.", "Já tenho alguém.", "Agora não é prioridade.", "Me manda informações."],
          framework: ["Agradeça e entenda: pergunte o que está por trás da objeção.", "Reconecte com o problema que a pessoa disse ter.", "Mostre o valor ou o custo de não resolver.", "Proponha um próximo passo pequeno e concreto."] },
        { type: "compare", before: "m08.antes", after: "m08.script", title: "Antes e depois" },
      ],
      output: { key: "m08.script", title: "Meu script" },
      community: "Qual objeção você mais ouve, e como está respondendo?",
      next: "Ler os sinais do que aconteceu.",
    },
    {
      key: "m09", title: "O mercado respondeu. E agora?", question: "O que as evidências estão dizendo?",
      blocks: [
        { type: "concept", title: "Ler resultados sem se enganar",
          what: "Compare o que aconteceu com a meta numérica que você definiu no módulo 6. Olhe também onde as pessoas pararam: não responderam; conversaram, mas não compraram; ou compraram.",
          why: "Cada ponto de parada sugere um ajuste diferente. Pouca resposta: canal ou mensagem. Conversa sem compra: oferta ou preço. Compra sem retorno: entrega.",
          example: "30 abordados, 12 responderam, 6 conversaram, 0 compraram, e todos disseram “caro”. O problema existe; a oferta ou o preço precisa mudar.",
          mistake: "Decidir pelo humor do dia ou mudar tudo ao mesmo tempo e não saber o que funcionou." },
        { type: "video", title: "Quando insistir e quando admitir que a ideia não funcionou" },
        { type: "fields", key: "m09.resultados", title: "Meus resultados", fields: [
          { k: "contatadas", l: "Pessoas contatadas" }, { k: "respostas", l: "Respostas" }, { k: "conversas", l: "Conversas" },
          { k: "ofertas", l: "Ofertas apresentadas" }, { k: "vendas", l: "Vendas" },
          { k: "objecoes", l: "Objeções", multiline: true }, { k: "feedback", l: "Feedback", multiline: true }] },
        { type: "decision", key: "m09.decisao", ask: "Qual decisão você está tomando, e por quê?", paths: [
          { k: "Continuar", when: "Pessoas pagaram ou se comprometeram de verdade, e o número que você definiu foi atingido." },
          { k: "Ajustar", when: "Houve interesse, mas as mesmas objeções se repetem. Mude uma coisa e teste de novo." },
          { k: "Abandonar", when: "Quase ninguém se interessou mesmo depois de ajustar. Você economizou tempo e dinheiro." }] },
      ],
      output: { key: "m09.decisao", title: "Minha decisão" },
      community: "Qual sinal fez você decidir?",
      next: "Transformar o que aprendeu em 30 dias de ação.",
    },
    {
      key: "m10", title: "Os próximos 30 dias", question: "O que vem agora, e o que fica para depois?",
      blocks: [
        { type: "concept", title: "Foco é escolher o que não fazer",
          what: "Depois da validação, a tentação é fazer tudo: logo, site, CNPJ, Instagram. Um plano de 30 dias define poucas prioridades e as métricas que mostram se estão funcionando.",
          why: "Energia é limitada. Três coisas bem feitas valem mais que dez começadas.",
          example: "Prioridade: fechar 5 clientes pagantes. Métrica: conversas por semana. Ação: ligar para os 8 que disseram “talvez”. Não fazer ainda: app próprio.",
          mistake: "Pular para operação e marca antes de ter clientes recorrentes." },
        { type: "video", title: "De validação para operação" },
        { type: "fields", key: "m10.plano", title: "Meus próximos 30 dias", help: "Revise seu espaço antes de preencher.", fields: [
          { k: "prioridades", l: "3 prioridades", multiline: true }, { k: "metricas", l: "3 métricas", multiline: true },
          { k: "acoes", l: "3 ações desta semana", multiline: true }, { k: "naofazer", l: "3 coisas para NÃO fazer ainda", multiline: true }] },
      ],
      output: { key: "m10.plano", title: "Meus próximos 30 dias" },
      community: "Qual é a primeira ação da sua semana?",
      next: "Revisar o projeto completo no seu espaço.",
    },
  ],
  finalPlan: {
    title: "Meu negócio — primeira versão",
    sections: [
      { t: "Hipótese", keys: ["m01.hipotese"] }, { t: "Cliente", keys: ["m02.cliente"] }, { t: "Evidências", keys: ["m03.evidencias", "m03.validador"] },
      { t: "Economia", keys: ["m04.economia"] }, { t: "Oferta", keys: ["m05.oferta"] }, { t: "Experimento", keys: ["m06.criterio", "m06.teste"] },
      { t: "Prospects", keys: ["m07.prospects"] }, { t: "Abordagem de venda", keys: ["m08.script"] },
      { t: "Resultados", keys: ["m09.resultados"] }, { t: "Decisão", keys: ["m09.decisao"] }, { t: "Próximos 30 dias", keys: ["m10.plano"] },
    ],
  },
};
