import type { Course } from "./types";

export const IA_TRABALHO: Course = {
  slug: "ia-no-trabalho",
  title: "IA no trabalho: do prompt ao processo",
  thesis: "Pare de usar IA apenas para fazer perguntas. Aprenda a transformar tarefas em processos melhores.",
  category: "Tecnologia & IA",
  difficulty: "Fundamentos",
  commitment: "8 módulos · cerca de 30 min de prática cada",
  project: "Meu workflow",
  outcomes: ["Critério para saber quando usar IA", "Um modelo de prompt estruturado", "Um inventário das suas tarefas", "Um assistente para uma tarefa real", "Um método de verificação", "Um fluxo com revisão humana", "Limites claros do que não automatizar", "Meu primeiro workflow com IA"],
  tools: ["Construtor de prompts", "Construtor de workflow"],
  next: [
    { slug: "vendas-da-conversa-ao-cliente", why: "Com tempo liberado, vale investir em conversas com clientes, onde a IA ajuda pouco." },
    { slug: "da-ideia-aos-primeiros-clientes", why: "IA acelera a execução, mas a validação de uma ideia ainda depende de pessoas reais." },
  ],
  modules: [
    {
      key: "ia01", title: "O que IA faz bem e o que faz mal", question: "Em quais tarefas vale confiar na IA?",
      blocks: [
        { type: "concept", title: "Boa em padrões, fraca em verdade",
          what: "Modelos de linguagem são bons em resumir, reescrever, organizar, gerar rascunhos e variações. São fracos em fatos recentes, contas precisas, contexto que não receberam e julgamento.",
          why: "Usar IA na tarefa errada gera retrabalho ou erros que passam despercebidos.",
          example: "Ótimo: transformar anotações bagunçadas de reunião num resumo com próximos passos. Arriscado: perguntar qual é a alíquota de imposto atual e usar sem conferir.",
          mistake: "Tratar a resposta da IA como pesquisa feita." },
        { type: "classify", key: "ia01.classificacao", prompt: "Para cada tarefa, a IA ajuda bem ou exige muito cuidado?", categories: ["Faz bem", "Exige cuidado"], items: [
          { t: "Reescrever um e-mail em tom mais cordial", a: "Faz bem" },
          { t: "Informar a cotação do dólar de hoje", a: "Exige cuidado", why: "Pode estar desatualizada ou inventada." },
          { t: "Gerar 10 ideias de título para um post", a: "Faz bem" },
          { t: "Decidir se um funcionário deve ser demitido", a: "Exige cuidado", why: "Julgamento humano e impacto sobre pessoas." },
          { t: "Resumir um documento longo que você colou", a: "Faz bem" },
          { t: "Citar a lei exata que se aplica ao seu caso", a: "Exige cuidado", why: "Modelos podem inventar referências." }] },
        { type: "video", title: "O que IA realmente faz" },
      ],
      output: { key: "ia01.classificacao", title: "Meu critério de uso" },
      community: "Qual foi o erro mais curioso que uma IA já cometeu com você?",
      next: "Aprender a pedir antes de escrever o prompt.",
    },
    {
      key: "ia02", title: "Pare de começar pelo prompt", question: "O que você quer, antes de saber como pedir?",
      blocks: [
        { type: "concept", title: "Objetivo, contexto, entrada, restrições e saída",
          what: "Um bom pedido define o objetivo (para que serve), o contexto (quem, onde), a entrada (o material), as restrições (tom, tamanho, o que evitar) e a saída (formato esperado).",
          why: "A qualidade da resposta depende muito mais da clareza do pedido do que de “palavras mágicas”.",
          example: "Em vez de “escreva um post sobre meu café”: “Objetivo: atrair clientes no fim da tarde. Contexto: café de bairro em BH, público de 25-40 anos. Entrada: temos happy hour de café gelado das 16h às 18h. Restrições: tom leve, sem emojis, até 80 palavras. Saída: 3 opções.”",
          mistake: "Pedir algo vago, receber algo genérico e concluir que “IA não serve”." },
        { type: "video", title: "Pensar antes de pedir" },
        { type: "fields", key: "ia02.prompt", title: "Construtor de prompt", help: "Use uma tarefa real da sua semana.", fields: [
          { k: "objetivo", l: "Objetivo" }, { k: "contexto", l: "Contexto", multiline: true }, { k: "entrada", l: "Entrada", multiline: true },
          { k: "restricoes", l: "Restrições" }, { k: "saida", l: "Saída esperada" }] },
      ],
      output: { key: "ia02.prompt", title: "Meu prompt estruturado" },
      community: "Compartilhe um pedido que funcionou muito melhor depois que você deu contexto.",
      next: "Encontrar o trabalho repetitivo da sua semana.",
    },
    {
      key: "ia03", title: "Encontre trabalho repetitivo", question: "Onde vai o seu tempo numa semana normal?",
      blocks: [
        { type: "concept", title: "Comece pelo que se repete",
          what: "Tarefas repetitivas, administrativas e de comunicação costumam ser as melhores candidatas para IA. Tarefas de decisão e criativas pedem mais cuidado.",
          why: "Automatizar algo que você faz uma vez por ano não muda nada. Automatizar algo diário muda a semana.",
          example: "Responder dúvidas parecidas de clientes, montar relatório semanal, transformar áudio em resumo, organizar planilha de pedidos.",
          mistake: "Começar pelo projeto mais ambicioso, em vez da tarefa chata que se repete." },
        { type: "video", title: "Onde a IA economiza tempo de verdade" },
        { type: "groups", key: "ia03.tarefas", title: "Minhas tarefas da semana", help: "Liste tarefas reais em cada tipo.", ph: "Tarefa", groups: ["Repetitivas", "Decisão", "Criativas", "Administrativas", "Comunicação"] },
      ],
      output: { key: "ia03.tarefas", title: "Inventário de tarefas" },
      community: "Qual tarefa repetitiva você mais gostaria de não fazer à mão?",
      next: "Montar um assistente para uma tarefa.",
    },
    {
      key: "ia04", title: "IA como assistente", question: "Que tarefa você pode delegar parcialmente esta semana?",
      blocks: [
        { type: "concept", title: "Assistente, não substituto",
          what: "Um fluxo de assistente define: qual tarefa, que instruções fixas a IA recebe, que material você fornece a cada vez e o que você revisa no final.",
          why: "Instruções fixas tornam o resultado previsível e economizam tempo de reescrever o pedido toda vez.",
          example: "Assistente de propostas: instruções com tom, estrutura e preços; a cada cliente você cola as anotações da conversa; revisa valores e prazos antes de enviar.",
          mistake: "Enviar o resultado direto, sem revisão." },
        { type: "video", title: "Seu primeiro assistente" },
        { type: "fields", key: "ia04.assistente", title: "Meu assistente", fields: [
          { k: "tarefa", l: "Tarefa" }, { k: "instrucoes", l: "Instruções fixas", multiline: true },
          { k: "material", l: "Material que forneço a cada vez" }, { k: "revisao", l: "O que eu sempre reviso" }] },
      ],
      output: { key: "ia04.assistente", title: "Meu assistente" },
      community: "Que tarefa você já delega para IA, e o que ainda revisa sempre?",
      next: "Usar IA para pesquisar sem confiar cegamente.",
    },
    {
      key: "ia05", title: "IA para pesquisa e decisão", question: "Como saber se a resposta está certa?",
      blocks: [
        { type: "concept", title: "Verificar é parte do trabalho",
          what: "IA pode ajudar a mapear opções, levantar perguntas e organizar argumentos. Fatos, números e fontes precisam ser verificados em lugares confiáveis.",
          why: "Modelos escrevem com a mesma confiança quando acertam e quando erram.",
          example: "Use IA para listar “o que devo considerar ao escolher um sistema de gestão”. Depois confira preços e funcionalidades nos sites oficiais.",
          mistake: "Pedir “qual é a melhor opção?” e seguir a resposta sem entender o raciocínio." },
        { type: "video", title: "Confiar, mas verificar" },
        { type: "fields", key: "ia05.verificacao", title: "Meu método de verificação", fields: [
          { k: "pergunta", l: "Uma decisão real em que vou usar IA" }, { k: "pedir", l: "O que vou pedir para a IA", multiline: true },
          { k: "conferir", l: "O que preciso conferir em outra fonte", multiline: true }, { k: "fontes", l: "Onde vou conferir" }] },
      ],
      output: { key: "ia05.verificacao", title: "Meu método de verificação" },
      community: "Como você confere se uma informação da IA está correta?",
      next: "Desenhar um processo com IA e revisão humana.",
    },
    {
      key: "ia06", title: "IA + processos", question: "Onde entra a IA e onde entra você?",
      blocks: [
        { type: "concept", title: "Entrada → IA → revisão humana → ação",
          what: "Um workflow com IA tem quatro partes: o que entra, o que a IA faz, o que uma pessoa revisa e a ação que acontece no final.",
          why: "Deixar explícito onde está a revisão humana evita que erros cheguem ao cliente.",
          example: "Entrada: e-mail de cliente. IA: classifica o assunto e sugere resposta. Revisão: você ajusta e aprova. Ação: resposta enviada e pedido registrado na planilha.",
          mistake: "Pular a revisão porque “funcionou nas últimas vezes”." },
        { type: "video", title: "De tarefa a processo" },
        { type: "fields", key: "ia06.fluxo", title: "Meu fluxo", fields: [
          { k: "entrada", l: "Entrada", ph: "O que chega" }, { k: "ia", l: "IA", ph: "O que a IA faz" },
          { k: "revisao", l: "Revisão humana", ph: "O que você confere" }, { k: "acao", l: "Ação", ph: "O que acontece no final" }] },
      ],
      output: { key: "ia06.fluxo", title: "Meu fluxo" },
      community: "Em que ponto do seu fluxo a revisão humana é indispensável?",
      next: "Definir o que não automatizar.",
    },
    {
      key: "ia07", title: "O que não automatizar", question: "Onde a IA não deveria decidir por você?",
      blocks: [
        { type: "concept", title: "Limites são parte do processo",
          what: "Algumas áreas pedem cuidado redobrado: privacidade, decisões financeiras, dados sensíveis, julgamento crítico e relações humanas.",
          why: "Um erro nessas áreas pode custar dinheiro, confiança ou expor pessoas.",
          example: "Colar a planilha de clientes com CPF e telefone numa ferramenta pública. Ou deixar a IA responder sozinha a uma reclamação delicada.",
          mistake: "Achar que, se a ferramenta permite, está tudo bem." },
        { type: "choices", key: "ia07.riscos", prompt: "Quais desses riscos existem no seu trabalho?", multi: true, options: ["Privacidade", "Decisões financeiras", "Dados sensíveis", "Julgamento crítico", "Relações humanas"] },
        { type: "video", title: "Onde a IA não deve decidir" },
        { type: "question", key: "ia07.regras", prompt: "Escreva suas regras: o que você nunca vai colocar numa IA ou deixar a IA decidir sozinha?" },
      ],
      output: { key: "ia07.regras", title: "Minhas regras" },
      community: "Que limite você definiu para o uso de IA no seu trabalho?",
      next: "Montar seu primeiro workflow completo.",
    },
    {
      key: "ia08", title: "Meu primeiro workflow", question: "Que processo você vai melhorar a partir de amanhã?",
      blocks: [
        { type: "concept", title: "Um workflow pequeno, medido",
          what: "Seu primeiro workflow resolve um problema específico, deixa claro o papel da IA e o seu, e tem uma métrica para saber se melhorou.",
          why: "Sem métrica, você não sabe se ganhou tempo ou só mudou de lugar o trabalho.",
          example: "Problema: relatório semanal leva 2 horas. Métrica: levar menos de 40 minutos, sem erros de número, por 4 semanas seguidas.",
          mistake: "Montar o fluxo e não medir nada." },
        { type: "video", title: "Do prompt ao processo" },
        { type: "fields", key: "ia08.workflow", title: "Meu workflow com IA", fields: [
          { k: "problema", l: "Problema" }, { k: "atual", l: "Processo atual", multiline: true },
          { k: "papel_ia", l: "Papel da IA" }, { k: "papel_humano", l: "Papel humano" },
          { k: "entrada", l: "Entrada" }, { k: "saida", l: "Saída" },
          { k: "revisao", l: "Revisão" }, { k: "metrica", l: "Métrica de sucesso" }] },
      ],
      output: { key: "ia08.workflow", title: "Meu workflow com IA" },
      community: "Qual processo você automatizou e quanto tempo ganhou?",
      next: "Revisar seu workflow no seu espaço.",
    },
  ],
  finalPlan: {
    title: "Meu primeiro workflow com IA",
    sections: [
      { t: "Critério de uso", keys: ["ia01.classificacao"] }, { t: "Prompt estruturado", keys: ["ia02.prompt"] }, { t: "Tarefas", keys: ["ia03.tarefas"] },
      { t: "Assistente", keys: ["ia04.assistente"] }, { t: "Verificação", keys: ["ia05.verificacao"] }, { t: "Fluxo", keys: ["ia06.fluxo"] },
      { t: "Limites", keys: ["ia07.riscos", "ia07.regras"] }, { t: "Workflow", keys: ["ia08.workflow"] },
    ],
  },
};
