import type { Course } from "./types";

export const NETWORKING: Course = {
  slug: "networking-do-zero",
  title: "Networking do zero",
  thesis: "Como construir relações profissionais quando você ainda não conhece as pessoas certas.",
  category: "Networking",
  difficulty: "Fundamentos",
  commitment: "8 módulos · cerca de 30 min de prática cada",
  project: "Minha rede",
  outcomes: ["Um retrato honesto da sua rede atual", "Meu mapa de relacionamentos", "Clareza sobre o valor que você oferece", "Uma mensagem de abordagem reescrita", "5 ambientes para estar presente", "Um plano de contribuição de 30 dias", "Uma lista de quem retomar contato", "Meu plano de networking de 90 dias"],
  tools: ["Mapa de relacionamentos", "Rastreador de contatos"],
  next: [
    { slug: "vendas-da-conversa-ao-cliente", why: "Relações abrem portas. Saber conduzir uma boa conversa ajuda a transformar isso em oportunidade." },
    { slug: "da-ideia-aos-primeiros-clientes", why: "Sua rede é o lugar mais barato para testar uma ideia de negócio." },
  ],
  modules: [
    {
      key: "n01", title: "Networking não é colecionar contatos", question: "Como sua rede realmente é hoje?",
      blocks: [
        { type: "concept", title: "Relação, não transação",
          what: "Networking é construir relações em que as duas partes se conhecem, confiam e se ajudam ao longo do tempo. Não é juntar cartões, conexões ou seguidores.",
          why: "Oportunidades costumam chegar por indicação. E ninguém indica quem só aparece quando precisa de algo.",
          example: "500 conexões no LinkedIn que nunca falaram com você valem menos que 10 pessoas que lembrariam do seu nome quando surgisse uma vaga.",
          mistake: "Abordar alguém já pedindo emprego, investimento ou favor. Isso transforma a pessoa em meio, e ela percebe." },
        { type: "video", title: "Networking sem ser interesseiro" },
        { type: "fields", key: "n01.retrato", title: "Minha rede hoje", fields: [
          { k: "conversa", l: "Com quantas pessoas do meu campo eu converso pelo menos uma vez por mês?" },
          { k: "ajudei", l: "Quem eu ajudei profissionalmente nos últimos 3 meses?" },
          { k: "pediria", l: "A quem eu poderia pedir uma indicação amanhã?" },
          { k: "sensacao", l: "Como me sinto sobre fazer networking?", options: ["Desconfortável", "Não sei por onde começar", "Faço, mas sem método", "Gosto, quero organizar"] }] },
      ],
      output: { key: "n01.retrato", title: "Minha rede hoje" },
      community: "O que te deixa desconfortável quando pensa em “fazer networking”?",
      next: "Desenhar o mapa das pessoas que você já conhece.",
    },
    {
      key: "n02", title: "Seu mapa atual", question: "Quem você já conhece, e esqueceu que conhece?",
      blocks: [
        { type: "concept", title: "Laços fortes e laços fracos",
          what: "Laços fortes são pessoas próximas. Laços fracos são conhecidos: ex-colegas, amigos de amigos, gente de um curso. Os dois importam de formas diferentes.",
          why: "Laços fracos circulam em outros ambientes e por isso trazem informações e oportunidades que seu círculo próximo não vê.",
          example: "A vaga que mudou a carreira de muita gente veio de um ex-colega da faculdade com quem não falavam havia anos.",
          mistake: "Achar que “não conhece ninguém” sem nunca ter listado as pessoas." },
        { type: "video", title: "A rede que você já tem" },
        { type: "groups", key: "n02.mapa", title: "Meu mapa de relacionamentos", help: "Adicione nomes ou iniciais. Só você vê.", ph: "Nome", groups: ["Família", "Amigos", "Trabalho", "Clientes", "Fornecedores", "Online", "Conhecidos", "Pessoas que quero conhecer"] },
      ],
      output: { key: "n02.mapa", title: "Meu mapa de relacionamentos" },
      community: "Qual grupo do seu mapa te surpreendeu: maior ou menor do que imaginava?",
      next: "Descobrir o que você tem para oferecer.",
    },
    {
      key: "n03", title: "O que você tem para oferecer?", question: "Por que alguém ia querer conversar com você?",
      blocks: [
        { type: "concept", title: "Todo mundo tem algo a oferecer",
          what: "Valor não é só dinheiro ou cargo. É conhecimento, tempo, curiosidade, uma apresentação, um feedback honesto, uma experiência que o outro ainda não viveu.",
          why: "Quem sabe o que pode oferecer aborda as pessoas com segurança, e as relações ficam equilibradas.",
          example: "Uma estudante de design sem experiência ofereceu revisar o portfólio de três profissionais em troca de 15 minutos de conversa. Dois viraram contatos frequentes.",
          mistake: "Achar que só pode fazer networking “depois de ser alguém”." },
        { type: "video", title: "Seu valor antes do seu currículo" },
        { type: "fields", key: "n03.valor", title: "Meu valor para a rede", fields: [
          { k: "sei", l: "O que você sabe?", multiline: true }, { k: "resolvo", l: "Que problema consegue resolver?" },
          { k: "apresento", l: "Quem consegue apresentar?" }, { k: "experiencia", l: "Que experiência possui?" },
          { k: "gratis", l: "Como poderia ajudar alguém gratuitamente?" }] },
      ],
      output: { key: "n03.valor", title: "Meu valor para a rede" },
      community: "Que ajuda simples você poderia oferecer a alguém aqui da comunidade esta semana?",
      next: "Escrever a primeira mensagem para alguém que você admira.",
    },
    {
      key: "n04", title: "Como abordar alguém", question: "Como começar uma conversa sem parecer que está pedindo algo?",
      blocks: [
        { type: "question", key: "n04.antes", prompt: "Você admira o trabalho de alguém e quer iniciar uma conversa. Escreva a mensagem que mandaria hoje." },
        { type: "concept", title: "Contexto, especificidade, relevância e pedido leve",
          what: "Uma boa abordagem diz de onde você conhece a pessoa (contexto), cita algo concreto do trabalho dela (especificidade), mostra por que você está falando com ela e não com outra (relevância) e termina com um pedido fácil de aceitar.",
          why: "Pessoas ocupadas respondem mensagens curtas, específicas e que não exigem muito delas.",
          example: "“Oi, Marina. Li seu texto sobre precificação para freelancers e apliquei a ideia de pacote fechado: fechei meu primeiro cliente assim. Posso te mandar uma pergunta curta sobre como você define o escopo?”",
          mistake: "“Oi, tudo bem? Podemos tomar um café?” Sem contexto, sem motivo, e com um pedido que custa uma hora da pessoa." },
        { type: "video", title: "A primeira mensagem" },
        { type: "question", key: "n04.depois", prompt: "Reescreva sua mensagem com contexto, especificidade, relevância e um pedido leve." },
        { type: "compare", before: "n04.antes", after: "n04.depois", title: "Antes e depois" },
      ],
      output: { key: "n04.depois", title: "Minha mensagem de abordagem" },
      community: "Qual foi a melhor mensagem de abordagem que você já recebeu?",
      next: "Escolher os ambientes onde as relações acontecem.",
    },
    {
      key: "n05", title: "Ambientes", question: "Onde estão as pessoas que você quer conhecer?",
      blocks: [
        { type: "concept", title: "Relações nascem da proximidade",
          what: "Relações surgem em ambientes onde as pessoas se veem repetidas vezes: trabalho, comunidades, eventos, clientes, fornecedores, internet, amigos de amigos.",
          why: "Encontrar alguém uma vez raramente cria uma relação. Estar presente no mesmo lugar várias vezes, sim.",
          example: "Em vez de ir a 10 eventos diferentes, frequentar o mesmo encontro mensal por seis meses e virar a pessoa que todo mundo reconhece.",
          mistake: "Escolher ambientes pelo prestígio e não pelo seu objetivo." },
        { type: "video", title: "Onde as relações acontecem" },
        { type: "list", key: "n05.ambientes", title: "5 ambientes para o meu objetivo", max: 5, statusLabel: "Situação", statuses: ["Ainda não frequento", "Comecei", "Frequento sempre"],
          fields: [{ k: "ambiente", l: "Ambiente" }, { k: "tipo", l: "Tipo", ph: "Evento, comunidade, online…" }, { k: "porque", l: "Por que é relevante?" }, { k: "frequencia", l: "Com que frequência posso estar lá?" }] },
      ],
      output: { key: "n05.ambientes", title: "Meus ambientes" },
      community: "Qual comunidade ou evento fez diferença real para você?",
      next: "Construir reputação antes de pedir qualquer coisa.",
    },
    {
      key: "n06", title: "Reputação antes do pedido", question: "O que as pessoas lembram de você?",
      blocks: [
        { type: "concept", title: "Contribuir antes de pedir",
          what: "Reputação se constrói com ações visíveis e repetidas: contribuir, mostrar seu trabalho, responder dúvidas, apresentar pessoas, compartilhar o que aprendeu, ajudar.",
          why: "Quando chega a hora de pedir algo, quem já contribuiu é atendido com boa vontade.",
          example: "Responder uma pergunta por semana na comunidade e publicar um aprendizado por mês. Em três meses, as pessoas já sabem do que você entende.",
          mistake: "Contribuir só uma vez e esperar retorno imediato." },
        { type: "video", title: "Reputação é o que você faz quando ninguém está pedindo" },
        { type: "fields", key: "n06.plano", title: "Meu plano de contribuição de 30 dias", fields: [
          { k: "contribuir", l: "Onde vou contribuir?" }, { k: "mostrar", l: "Que trabalho vou mostrar?" },
          { k: "responder", l: "Que perguntas posso responder?" }, { k: "apresentar", l: "Quem posso apresentar a quem?" },
          { k: "compartilhar", l: "O que vou compartilhar?" }, { k: "ajudar", l: "Quem vou ajudar?" }] },
      ],
      output: { key: "n06.plano", title: "Meu plano de contribuição de 30 dias" },
      community: "O que você aprendeu este mês que poderia compartilhar aqui?",
      next: "Manter as relações vivas.",
    },
    {
      key: "n07", title: "Manter relacionamentos", question: "Quem você deveria procurar esta semana?",
      blocks: [
        { type: "concept", title: "Relações esfriam sem contato",
          what: "Manter uma relação é lembrar da pessoa sem precisar de motivo: agradecer, parabenizar, ajudar, retomar contato, apresentar alguém.",
          why: "Uma mensagem simples a cada poucos meses mantém a relação viva. Reaparecer só para pedir algo, não.",
          example: "“Vi que você lançou o novo projeto. Parabéns! Lembrei da nossa conversa do ano passado.” Leva 30 segundos.",
          mistake: "Depender da memória. Sem uma lista, você só fala com quem já está por perto." },
        { type: "video", title: "Follow-up sem ser chato" },
        { type: "groups", key: "n07.rastreador", title: "Quem eu devo…", ph: "Nome", groups: ["Agradecer", "Parabenizar", "Ajudar", "Retomar contato", "Apresentar"] },
      ],
      output: { key: "n07.rastreador", title: "Meu rastreador de relacionamentos" },
      community: "Para quem você vai mandar uma mensagem de agradecimento hoje?",
      next: "Juntar tudo num plano de 90 dias.",
    },
    {
      key: "n08", title: "Sua rede nos próximos 90 dias", question: "Como sua rede pode estar daqui a três meses?",
      blocks: [
        { type: "concept", title: "Pequeno, constante e intencional",
          what: "Um plano de networking define poucas pessoas, poucos ambientes e um ritmo possível de manter.",
          why: "Constância vence intensidade. Duas conversas por semana durante 90 dias são mais de 20 relações novas ou renovadas.",
          example: "Objetivo: migrar para produto. 8 pessoas a conhecer, 2 comunidades, 1 contribuição por semana, 3 apresentações por mês.",
          mistake: "Planos grandes demais que duram duas semanas." },
        { type: "video", title: "Sua rede como projeto" },
        { type: "fields", key: "n08.plano", title: "Meu plano de networking", fields: [
          { k: "pessoas", l: "Pessoas", multiline: true }, { k: "ambientes", l: "Ambientes", multiline: true },
          { k: "contribuicoes", l: "Contribuições", multiline: true }, { k: "apresentacoes", l: "Apresentações", multiline: true },
          { k: "followups", l: "Follow-ups", multiline: true }, { k: "acoes", l: "Ações para os 90 dias", multiline: true }] },
      ],
      output: { key: "n08.plano", title: "Meu plano de networking" },
      community: "Qual é a primeira pessoa que você vai procurar nos próximos 90 dias, e por quê?",
      next: "Revisar sua rede no seu espaço.",
    },
  ],
  finalPlan: {
    title: "Minha rede — plano de 90 dias",
    sections: [
      { t: "Ponto de partida", keys: ["n01.retrato"] }, { t: "Mapa", keys: ["n02.mapa"] }, { t: "Meu valor", keys: ["n03.valor"] },
      { t: "Abordagem", keys: ["n04.depois"] }, { t: "Ambientes", keys: ["n05.ambientes"] }, { t: "Contribuição", keys: ["n06.plano"] },
      { t: "Manutenção", keys: ["n07.rastreador"] }, { t: "Plano de 90 dias", keys: ["n08.plano"] },
    ],
  },
};
