import type { Course } from "./types";

export const VENDAS: Course = {
  slug: "vendas-da-conversa-ao-cliente",
  title: "Vendas: da conversa ao cliente",
  thesis: "Venda sem decorar frases: entenda problema, valor, objeção e decisão.",
  category: "Vendas",
  difficulty: "Fundamentos",
  commitment: "8 módulos · cerca de 30 min de prática cada",
  project: "Meu playbook",
  outcomes: ["Os motivos reais de compra do seu cliente", "Perguntas de descoberta", "Um diagnóstico de problema", "Uma proposta de valor", "Uma estrutura de apresentação", "Respostas para objeções", "Uma sequência de follow-up", "Meu playbook de vendas"],
  tools: ["Simulador de objeções", "Construtor de perguntas"],
  next: [
    { slug: "networking-do-zero", why: "Quem vende bem precisa de uma rede que indique e abra portas." },
    { slug: "ia-no-trabalho", why: "Boa parte do follow-up e da preparação de propostas pode virar um processo com IA e revisão humana." },
  ],
  modules: [
    {
      key: "v01", title: "Por que alguém compra?", question: "O que precisa ser verdade para alguém dizer sim?",
      blocks: [
        { type: "concept", title: "Necessidade, problema, desejo, risco e momento",
          what: "Uma compra acontece quando existe necessidade ou problema, há desejo pelo resultado, o risco parece aceitável e o momento é certo. Se um desses falta, a venda trava.",
          why: "Saber qual peça falta muda o que você faz: às vezes é preciso reduzir risco, não baixar preço.",
          example: "Um restaurante sabe que precisa de delivery (problema), quer faturar mais (desejo), mas tem medo de perder qualidade (risco) e está em reforma (momento). Insistir agora não adianta.",
          mistake: "Achar que toda venda perdida foi por preço." },
        { type: "video", title: "Por que as pessoas compram" },
        { type: "fields", key: "v01.motivos", title: "Por que meu cliente compra", fields: [
          { k: "necessidade", l: "Necessidade" }, { k: "problema", l: "Problema" }, { k: "desejo", l: "Desejo" },
          { k: "risco", l: "Risco percebido" }, { k: "momento", l: "Momento ideal" }] },
      ],
      output: { key: "v01.motivos", title: "Por que meu cliente compra" },
      community: "Qual foi a última coisa que você comprou depois de muito hesitar, e o que te fez decidir?",
      next: "Aprender a perguntar antes de apresentar.",
    },
    {
      key: "v02", title: "Perguntar antes de apresentar", question: "Quais perguntas revelam do que o cliente precisa?",
      blocks: [
        { type: "concept", title: "Perguntas de descoberta",
          what: "Perguntas abertas que ajudam o cliente a explicar a situação atual, o problema, o impacto e o que já tentou.",
          why: "Quem pergunta bem entende o problema melhor do que o próprio cliente explicaria sozinho e consegue apresentar a solução nas palavras dele.",
          example: "“Como vocês fazem isso hoje?”, “O que acontece quando dá errado?”, “Quanto tempo isso toma por semana?”, “O que já tentaram?”",
          mistake: "Perguntas que só servem para chegar ao seu produto (“Você não gostaria de economizar tempo?”)." },
        { type: "video", title: "A pergunta certa vende mais que o argumento certo" },
        { type: "fields", key: "v02.perguntas", title: "Minhas perguntas de descoberta", fields: [
          { k: "situacao", l: "Sobre a situação atual", multiline: true }, { k: "problema", l: "Sobre o problema", multiline: true },
          { k: "impacto", l: "Sobre o impacto", multiline: true }, { k: "tentativas", l: "Sobre o que já tentou", multiline: true },
          { k: "decisao", l: "Sobre como decide", multiline: true }] },
      ],
      output: { key: "v02.perguntas", title: "Minhas perguntas de descoberta" },
      community: "Qual pergunta mais abre conversa com os seus clientes?",
      next: "Entender o problema de verdade.",
    },
    {
      key: "v03", title: "Entender o problema", question: "O problema de que o cliente fala é o problema real?",
      blocks: [
        { type: "concept", title: "Sintoma e causa",
          what: "O cliente costuma descrever um sintoma. O problema real está um ou dois “porquês” abaixo.",
          why: "Resolver o sintoma gera cliente insatisfeito. Resolver a causa gera indicação.",
          example: "“Preciso de mais seguidores” (sintoma). Por quê? “Para vender mais.” Por que não vende? “Quem chega ao perfil não entende o que eu faço.” O problema é clareza, não alcance.",
          mistake: "Aceitar o primeiro problema que o cliente relata e já apresentar a solução." },
        { type: "classify", key: "v03.cenarios", prompt: "Cada cliente disse uma frase. É sintoma ou causa?", categories: ["Sintoma", "Causa"], items: [
          { t: "“Minhas vendas caíram.”", a: "Sintoma", why: "Falta descobrir por quê." },
          { t: "“Nosso vendedor sênior saiu e ninguém faz follow-up.”", a: "Causa" },
          { t: "“Preciso de um site novo.”", a: "Sintoma", why: "O site é a solução que a pessoa imaginou." },
          { t: "“Os clientes desistem no passo do pagamento.”", a: "Causa" },
          { t: "“A equipe vive apagando incêndio.”", a: "Sintoma" }] },
        { type: "video", title: "O problema por trás do problema" },
        { type: "fields", key: "v03.diagnostico", title: "Diagnóstico de um cliente real", fields: [
          { k: "disse", l: "O que o cliente disse" }, { k: "porques", l: "Os “porquês” que perguntei", multiline: true },
          { k: "real", l: "Qual parece ser o problema real" }, { k: "custo", l: "Quanto esse problema custa para ele" }] },
      ],
      output: { key: "v03.diagnostico", title: "Diagnóstico do problema" },
      community: "Conte um caso em que o problema real era diferente do que o cliente pediu.",
      next: "Traduzir características em resultados.",
    },
    {
      key: "v04", title: "Construir valor", question: "O que muda na vida do cliente depois que ele compra?",
      blocks: [
        { type: "concept", title: "Característica, benefício, resultado",
          what: "Característica é o que o produto tem. Benefício é o que isso permite. Resultado é a mudança concreta na vida ou no negócio do cliente.",
          why: "Clientes pagam por resultados. Quanto mais concretos e mensuráveis forem os resultados, mais fácil será perceber valor.",
          example: "Característica: agenda online. Benefício: o cliente marca sozinho. Resultado: a recepcionista ganha 2 horas por dia e o salão para de perder horários por telefone ocupado.",
          mistake: "Listar funcionalidades e esperar que o cliente faça a tradução." },
        { type: "video", title: "Valor é o que o cliente percebe" },
        { type: "fields", key: "v04.valor", title: "Minha proposta de valor", fields: [
          { k: "c1", l: "Característica 1 → resultado", multiline: true }, { k: "c2", l: "Característica 2 → resultado", multiline: true },
          { k: "c3", l: "Característica 3 → resultado", multiline: true }, { k: "frase", l: "Em uma frase: ajudo [quem] a [resultado] sem [dor]" }] },
      ],
      output: { key: "v04.valor", title: "Minha proposta de valor" },
      community: "Compartilhe sua frase de proposta de valor e peça para alguém dizer o que entendeu.",
      next: "Apresentar a oferta.",
    },
    {
      key: "v05", title: "Apresentar uma oferta", question: "Como apresentar sem virar um monólogo?",
      blocks: [
        { type: "concept", title: "Apresentar é conectar com o que o cliente disse",
          what: "Uma boa apresentação retoma o problema nas palavras do cliente, mostra como a oferta resolve, diz o preço com clareza e propõe um próximo passo.",
          why: "Quando o cliente se reconhece na apresentação, o preço vira consequência, não susto.",
          example: "“Você disse que perde 3 horas por semana montando escala. Nosso serviço monta e envia a escala toda sexta. São R$300 por mês. Quer testar no próximo mês com a equipe da manhã?”",
          mistake: "Esconder o preço até o fim ou pedir desculpas ao falar dele." },
        { type: "video", title: "Apresentar sem empurrar" },
        { type: "fields", key: "v05.apresentacao", title: "Minha estrutura de apresentação", fields: [
          { k: "retomar", l: "Retomar o problema (nas palavras do cliente)", multiline: true }, { k: "solucao", l: "Como a oferta resolve", multiline: true },
          { k: "prova", l: "Prova ou exemplo" }, { k: "preco", l: "Preço e condições" }, { k: "passo", l: "Próximo passo proposto" }] },
      ],
      output: { key: "v05.apresentacao", title: "Minha estrutura de apresentação" },
      community: "Como você fala de preço sem se sentir desconfortável?",
      next: "Responder às objeções.",
    },
    {
      key: "v06", title: "Objeções", question: "O que o cliente quer dizer quando diz “não”?",
      blocks: [
        { type: "question", key: "v06.antes", prompt: "O cliente diz: “Vou comparar com outras opções.” Como você responderia hoje?" },
        { type: "concept", title: "Objeção é informação",
          what: "Uma objeção é o cliente dizendo o que ainda falta para decidir: confiança, clareza, orçamento, prioridade ou autoridade.",
          why: "Tratar objeção como ataque gera discussão. Tratar como informação gera conversa.",
          example: "“Não tenho orçamento” pode significar “não vejo valor suficiente” ou “quem tem orçamento é meu sócio”. Pergunte antes de responder.",
          mistake: "Ter uma frase pronta para cada objeção e usá-la sem entender o contexto." },
        { type: "video", title: "Como responder a objeções sem pressionar" },
        { type: "scenarios", key: "v06.objecoes", title: "Simulador de objeções", intro: "Responda a cada objeção usando o roteiro.",
          items: ["Está caro.", "Preciso pensar.", "Vou comparar.", "Não tenho orçamento.", "Agora não."],
          framework: ["Valide sem concordar: “Faz sentido querer…”.", "Pergunte o que está por trás.", "Reconecte com o problema e o valor.", "Proponha um passo que reduza o risco."] },
        { type: "compare", before: "v06.antes", after: "v06.objecoes", title: "Antes e depois" },
      ],
      output: { key: "v06.objecoes", title: "Minhas respostas a objeções" },
      community: "A qual objeção você ainda não sabe responder bem?",
      next: "Fazer follow-up sem perseguir.",
    },
    {
      key: "v07", title: "Follow-up sem perseguir", question: "Como retomar o contato com o cliente sem incomodar?",
      blocks: [
        { type: "concept", title: "Cada contato precisa trazer algo",
          what: "Um follow-up bom traz algo novo: um resumo, uma resposta, um exemplo, uma pergunta útil. Não só “e aí, pensou?”.",
          why: "A maioria das vendas não acontece no primeiro contato. E a maioria das pessoas desiste depois do primeiro silêncio.",
          example: "Dia 1: resumo da conversa. Dia 3: um caso parecido. Dia 7: uma pergunta sobre a decisão. Dia 14: encerramento educado, deixando a porta aberta.",
          mistake: "Sumir depois do primeiro “vou ver” ou mandar a mesma mensagem cinco vezes." },
        { type: "video", title: "A venda acontece no follow-up" },
        { type: "fields", key: "v07.sequencia", title: "Minha sequência de follow-up", fields: [
          { k: "d1", l: "Dia 1", multiline: true }, { k: "d3", l: "Dia 3", multiline: true },
          { k: "d7", l: "Dia 7", multiline: true }, { k: "d14", l: "Dia 14", multiline: true }] },
      ],
      output: { key: "v07.sequencia", title: "Minha sequência de follow-up" },
      community: "Qual follow-up que você recebeu te fez comprar?",
      next: "Juntar tudo no seu playbook.",
    },
    {
      key: "v08", title: "Meu playbook", question: "Como você vende, do primeiro contato ao fechamento?",
      blocks: [
        { type: "concept", title: "Um playbook é seu jeito de vender, escrito",
          what: "O playbook reúne perguntas, proposta de valor, estrutura de oferta, objeções, respostas e follow-up num só lugar.",
          why: "Escrito, ele pode ser melhorado a cada conversa e um dia ensinado a outra pessoa.",
          example: "Depois de 10 conversas, você percebe que a pergunta 3 sempre gera a melhor resposta e passa a usá-la primeiro.",
          mistake: "Escrever uma vez e nunca revisar." },
        { type: "video", title: "Vender como processo" },
        { type: "question", key: "v08.aprendizado", prompt: "Revise seu espaço. O que você mudaria no seu jeito de vender a partir de agora?" },
      ],
      output: { key: "v08.aprendizado", title: "O que muda no meu jeito de vender" },
      community: "Qual parte do seu playbook você vai testar primeiro?",
      next: "Revisar seu playbook completo no seu espaço.",
    },
  ],
  finalPlan: {
    title: "Meu playbook de vendas",
    sections: [
      { t: "Por que compram", keys: ["v01.motivos"] }, { t: "Perguntas de descoberta", keys: ["v02.perguntas"] }, { t: "Diagnóstico", keys: ["v03.diagnostico"] },
      { t: "Proposta de valor", keys: ["v04.valor"] }, { t: "Estrutura de oferta", keys: ["v05.apresentacao"] },
      { t: "Objeções e respostas", keys: ["v06.objecoes"] }, { t: "Follow-up", keys: ["v07.sequencia"] }, { t: "O que muda", keys: ["v08.aprendizado"] },
    ],
  },
};
