/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConhecaAComunidadeRouteImport } from './routes/conheca-a-comunidade'
import { Route as ConhecaOsEncontrosRouteImport } from './routes/conheca-os-encontros'
import { Route as DiretrizesRouteImport } from './routes/diretrizes'
import { Route as OportunidadesRouteImport } from './routes/oportunidades'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBoasVindasRouteImport } from './routes/_authenticated/boas-vindas'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMeusCursosRouteImport } from './routes/_authenticated/meus-cursos'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as CursosIndexRouteImport } from './routes/cursos.index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as GestorSlugRouteImport } from './routes/gestor.$slug'
import { Route as GestoresIndexRouteImport } from './routes/gestores.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAlunosRouteImport } from './routes/_authenticated/admin/alunos'
import { Route as AuthenticatedAdminComunidadeRouteImport } from './routes/_authenticated/admin/comunidade'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminEncontrosRouteImport } from './routes/_authenticated/admin/encontros'
import { Route as AuthenticatedAdminGestoresRouteImport } from './routes/_authenticated/admin/gestores'
import { Route as AuthenticatedAulaLessonIdRouteImport } from './routes/_authenticated/aula.$lessonId'
import { Route as AuthenticatedComunidadeIndexRouteImport } from './routes/_authenticated/comunidade.index'
import { Route as AuthenticatedComunidadePostIdRouteImport } from './routes/_authenticated/comunidade.$postId'
import { Route as AuthenticatedCursoSlugRouteImport } from './routes/_authenticated/curso.$slug'
import { Route as AuthenticatedEncontrosIndexRouteImport } from './routes/_authenticated/encontros.index'
import { Route as AuthenticatedEncontrosIdRouteImport } from './routes/_authenticated/encontros.$id'
import { Route as AuthenticatedGestoresIdRouteImport } from './routes/_authenticated/gestores.$id'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated/mensagens.index'
import { Route as AuthenticatedMensagensIdRouteImport } from './routes/_authenticated/mensagens.$id'
import { Route as AuthenticatedPessoasIndexRouteImport } from './routes/_authenticated/pessoas.index'
import { Route as AuthenticatedPessoasIdRouteImport } from './routes/_authenticated/pessoas.$id'
import { Route as AuthenticatedAdminCursosIndexRouteImport } from './routes/_authenticated/admin/cursos.index'
import { Route as AuthenticatedAdminCursosIdRouteImport } from './routes/_authenticated/admin/cursos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecaAComunidadeRoute = ConhecaAComunidadeRouteImport.update({
  id: '/conheca-a-comunidade',
  path: '/conheca-a-comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecaOsEncontrosRoute = ConhecaOsEncontrosRouteImport.update({
  id: '/conheca-os-encontros',
  path: '/conheca-os-encontros',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretrizesRoute = DiretrizesRouteImport.update({
  id: '/diretrizes',
  path: '/diretrizes',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesRoute = OportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoasVindasRoute = AuthenticatedBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusCursosRoute = AuthenticatedMeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorSlugRoute = GestorSlugRouteImport.update({
  id: '/gestor/$slug',
  path: '/gestor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GestoresIndexRoute = GestoresIndexRouteImport.update({
  id: '/gestores/',
  path: '/gestores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAlunosRoute =
  AuthenticatedAdminAlunosRouteImport.update({
    id: '/alunos',
    path: '/alunos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComunidadeRoute =
  AuthenticatedAdminComunidadeRouteImport.update({
    id: '/comunidade',
    path: '/comunidade',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEncontrosRoute =
  AuthenticatedAdminEncontrosRouteImport.update({
    id: '/encontros',
    path: '/encontros',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGestoresRoute =
  AuthenticatedAdminGestoresRouteImport.update({
    id: '/gestores',
    path: '/gestores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAulaLessonIdRoute =
  AuthenticatedAulaLessonIdRouteImport.update({
    id: '/aula/$lessonId',
    path: '/aula/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunidadeIndexRoute =
  AuthenticatedComunidadeIndexRouteImport.update({
    id: '/comunidade/',
    path: '/comunidade/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComunidadePostIdRoute =
  AuthenticatedComunidadePostIdRouteImport.update({
    id: '/comunidade/$postId',
    path: '/comunidade/$postId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursoSlugRoute = AuthenticatedCursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEncontrosIndexRoute =
  AuthenticatedEncontrosIndexRouteImport.update({
    id: '/encontros/',
    path: '/encontros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncontrosIdRoute =
  AuthenticatedEncontrosIdRouteImport.update({
    id: '/encontros/$id',
    path: '/encontros/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestoresIdRoute = AuthenticatedGestoresIdRouteImport.update({
  id: '/gestores/$id',
  path: '/gestores/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensIdRoute =
  AuthenticatedMensagensIdRouteImport.update({
    id: '/mensagens/$id',
    path: '/mensagens/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPessoasIndexRoute =
  AuthenticatedPessoasIndexRouteImport.update({
    id: '/pessoas/',
    path: '/pessoas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPessoasIdRoute = AuthenticatedPessoasIdRouteImport.update({
  id: '/pessoas/$id',
  path: '/pessoas/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCursosIndexRoute =
  AuthenticatedAdminCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCursosIdRoute =
  AuthenticatedAdminCursosIdRouteImport.update({
    id: '/cursos/$id',
    path: '/cursos/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conheca-a-comunidade': typeof ConhecaAComunidadeRoute
  '/conheca-os-encontros': typeof ConhecaOsEncontrosRoute
  '/diretrizes': typeof DiretrizesRoute
  '/oportunidades': typeof OportunidadesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trilhas': typeof TrilhasRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/gestor/$slug': typeof GestorSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/gestores/': typeof GestoresIndexRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/comunidade': typeof AuthenticatedAdminComunidadeRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/encontros': typeof AuthenticatedAdminEncontrosRoute
  '/admin/gestores': typeof AuthenticatedAdminGestoresRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/comunidade/$postId': typeof AuthenticatedComunidadePostIdRoute
  '/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/encontros/$id': typeof AuthenticatedEncontrosIdRoute
  '/gestores/$id': typeof AuthenticatedGestoresIdRoute
  '/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/comunidade/': typeof AuthenticatedComunidadeIndexRoute
  '/encontros/': typeof AuthenticatedEncontrosIndexRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/pessoas/': typeof AuthenticatedPessoasIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conheca-a-comunidade': typeof ConhecaAComunidadeRoute
  '/conheca-os-encontros': typeof ConhecaOsEncontrosRoute
  '/diretrizes': typeof DiretrizesRoute
  '/oportunidades': typeof OportunidadesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trilhas': typeof TrilhasRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/gestor/$slug': typeof GestorSlugRoute
  '/cursos': typeof CursosIndexRoute
  '/gestores': typeof GestoresIndexRoute
  '/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/admin/comunidade': typeof AuthenticatedAdminComunidadeRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/encontros': typeof AuthenticatedAdminEncontrosRoute
  '/admin/gestores': typeof AuthenticatedAdminGestoresRoute
  '/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/comunidade/$postId': typeof AuthenticatedComunidadePostIdRoute
  '/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/encontros/$id': typeof AuthenticatedEncontrosIdRoute
  '/gestores/$id': typeof AuthenticatedGestoresIdRoute
  '/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/comunidade': typeof AuthenticatedComunidadeIndexRoute
  '/encontros': typeof AuthenticatedEncontrosIndexRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/pessoas': typeof AuthenticatedPessoasIndexRoute
  '/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/conheca-a-comunidade': typeof ConhecaAComunidadeRoute
  '/conheca-os-encontros': typeof ConhecaOsEncontrosRoute
  '/diretrizes': typeof DiretrizesRoute
  '/oportunidades': typeof OportunidadesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trilhas': typeof TrilhasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/meus-cursos': typeof AuthenticatedMeusCursosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/gestor/$slug': typeof GestorSlugRoute
  '/cursos/': typeof CursosIndexRoute
  '/gestores/': typeof GestoresIndexRoute
  '/_authenticated/admin/alunos': typeof AuthenticatedAdminAlunosRoute
  '/_authenticated/admin/comunidade': typeof AuthenticatedAdminComunidadeRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/encontros': typeof AuthenticatedAdminEncontrosRoute
  '/_authenticated/admin/gestores': typeof AuthenticatedAdminGestoresRoute
  '/_authenticated/aula/$lessonId': typeof AuthenticatedAulaLessonIdRoute
  '/_authenticated/comunidade/$postId': typeof AuthenticatedComunidadePostIdRoute
  '/_authenticated/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/_authenticated/encontros/$id': typeof AuthenticatedEncontrosIdRoute
  '/_authenticated/gestores/$id': typeof AuthenticatedGestoresIdRoute
  '/_authenticated/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/_authenticated/pessoas/$id': typeof AuthenticatedPessoasIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/comunidade/': typeof AuthenticatedComunidadeIndexRoute
  '/_authenticated/encontros/': typeof AuthenticatedEncontrosIndexRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/pessoas/': typeof AuthenticatedPessoasIndexRoute
  '/_authenticated/admin/cursos/$id': typeof AuthenticatedAdminCursosIdRoute
  '/_authenticated/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conheca-a-comunidade'
    | '/conheca-os-encontros'
    | '/diretrizes'
    | '/oportunidades'
    | '/privacidade'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/trilhas'
    | '/admin'
    | '/boas-vindas'
    | '/inicio'
    | '/meus-cursos'
    | '/notificacoes'
    | '/perfil'
    | '/cursos/$slug'
    | '/gestor/$slug'
    | '/cursos/'
    | '/gestores/'
    | '/admin/alunos'
    | '/admin/comunidade'
    | '/admin/configuracoes'
    | '/admin/encontros'
    | '/admin/gestores'
    | '/aula/$lessonId'
    | '/comunidade/$postId'
    | '/curso/$slug'
    | '/encontros/$id'
    | '/gestores/$id'
    | '/mensagens/$id'
    | '/pessoas/$id'
    | '/admin/'
    | '/comunidade/'
    | '/encontros/'
    | '/mensagens/'
    | '/pessoas/'
    | '/admin/cursos/$id'
    | '/admin/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conheca-a-comunidade'
    | '/conheca-os-encontros'
    | '/diretrizes'
    | '/oportunidades'
    | '/privacidade'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/trilhas'
    | '/boas-vindas'
    | '/inicio'
    | '/meus-cursos'
    | '/notificacoes'
    | '/perfil'
    | '/cursos/$slug'
    | '/gestor/$slug'
    | '/cursos'
    | '/gestores'
    | '/admin/alunos'
    | '/admin/comunidade'
    | '/admin/configuracoes'
    | '/admin/encontros'
    | '/admin/gestores'
    | '/aula/$lessonId'
    | '/comunidade/$postId'
    | '/curso/$slug'
    | '/encontros/$id'
    | '/gestores/$id'
    | '/mensagens/$id'
    | '/pessoas/$id'
    | '/admin'
    | '/comunidade'
    | '/encontros'
    | '/mensagens'
    | '/pessoas'
    | '/admin/cursos/$id'
    | '/admin/cursos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/conheca-a-comunidade'
    | '/conheca-os-encontros'
    | '/diretrizes'
    | '/oportunidades'
    | '/privacidade'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/termos'
    | '/trilhas'
    | '/_authenticated/admin'
    | '/_authenticated/boas-vindas'
    | '/_authenticated/inicio'
    | '/_authenticated/meus-cursos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/cursos/$slug'
    | '/gestor/$slug'
    | '/cursos/'
    | '/gestores/'
    | '/_authenticated/admin/alunos'
    | '/_authenticated/admin/comunidade'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/encontros'
    | '/_authenticated/admin/gestores'
    | '/_authenticated/aula/$lessonId'
    | '/_authenticated/comunidade/$postId'
    | '/_authenticated/curso/$slug'
    | '/_authenticated/encontros/$id'
    | '/_authenticated/gestores/$id'
    | '/_authenticated/mensagens/$id'
    | '/_authenticated/pessoas/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/comunidade/'
    | '/_authenticated/encontros/'
    | '/_authenticated/mensagens/'
    | '/_authenticated/pessoas/'
    | '/_authenticated/admin/cursos/$id'
    | '/_authenticated/admin/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConhecaAComunidadeRoute: typeof ConhecaAComunidadeRoute
  ConhecaOsEncontrosRoute: typeof ConhecaOsEncontrosRoute
  DiretrizesRoute: typeof DiretrizesRoute
  OportunidadesRoute: typeof OportunidadesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TrilhasRoute: typeof TrilhasRoute
  CursosSlugRoute: typeof CursosSlugRoute
  GestorSlugRoute: typeof GestorSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
  GestoresIndexRoute: typeof GestoresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conheca-a-comunidade': {
      id: '/conheca-a-comunidade'
      path: '/conheca-a-comunidade'
      fullPath: '/conheca-a-comunidade'
      preLoaderRoute: typeof ConhecaAComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conheca-os-encontros': {
      id: '/conheca-os-encontros'
      path: '/conheca-os-encontros'
      fullPath: '/conheca-os-encontros'
      preLoaderRoute: typeof ConhecaOsEncontrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretrizes': {
      id: '/diretrizes'
      path: '/diretrizes'
      fullPath: '/diretrizes'
      preLoaderRoute: typeof DiretrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades': {
      id: '/oportunidades'
      path: '/oportunidades'
      fullPath: '/oportunidades'
      preLoaderRoute: typeof OportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boas-vindas': {
      id: '/_authenticated/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof AuthenticatedBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-cursos': {
      id: '/_authenticated/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof AuthenticatedMeusCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/$slug': {
      id: '/gestor/$slug'
      path: '/gestor/$slug'
      fullPath: '/gestor/$slug'
      preLoaderRoute: typeof GestorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestores/': {
      id: '/gestores/'
      path: '/gestores'
      fullPath: '/gestores/'
      preLoaderRoute: typeof GestoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/alunos': {
      id: '/_authenticated/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AuthenticatedAdminAlunosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comunidade': {
      id: '/_authenticated/admin/comunidade'
      path: '/comunidade'
      fullPath: '/admin/comunidade'
      preLoaderRoute: typeof AuthenticatedAdminComunidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/encontros': {
      id: '/_authenticated/admin/encontros'
      path: '/encontros'
      fullPath: '/admin/encontros'
      preLoaderRoute: typeof AuthenticatedAdminEncontrosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gestores': {
      id: '/_authenticated/admin/gestores'
      path: '/gestores'
      fullPath: '/admin/gestores'
      preLoaderRoute: typeof AuthenticatedAdminGestoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/aula/$lessonId': {
      id: '/_authenticated/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AuthenticatedAulaLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidade/': {
      id: '/_authenticated/comunidade/'
      path: '/comunidade'
      fullPath: '/comunidade/'
      preLoaderRoute: typeof AuthenticatedComunidadeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidade/$postId': {
      id: '/_authenticated/comunidade/$postId'
      path: '/comunidade/$postId'
      fullPath: '/comunidade/$postId'
      preLoaderRoute: typeof AuthenticatedComunidadePostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$slug': {
      id: '/_authenticated/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof AuthenticatedCursoSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encontros/': {
      id: '/_authenticated/encontros/'
      path: '/encontros'
      fullPath: '/encontros/'
      preLoaderRoute: typeof AuthenticatedEncontrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encontros/$id': {
      id: '/_authenticated/encontros/$id'
      path: '/encontros/$id'
      fullPath: '/encontros/$id'
      preLoaderRoute: typeof AuthenticatedEncontrosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestores/$id': {
      id: '/_authenticated/gestores/$id'
      path: '/gestores/$id'
      fullPath: '/gestores/$id'
      preLoaderRoute: typeof AuthenticatedGestoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/$id': {
      id: '/_authenticated/mensagens/$id'
      path: '/mensagens/$id'
      fullPath: '/mensagens/$id'
      preLoaderRoute: typeof AuthenticatedMensagensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas/': {
      id: '/_authenticated/pessoas/'
      path: '/pessoas'
      fullPath: '/pessoas/'
      preLoaderRoute: typeof AuthenticatedPessoasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas/$id': {
      id: '/_authenticated/pessoas/$id'
      path: '/pessoas/$id'
      fullPath: '/pessoas/$id'
      preLoaderRoute: typeof AuthenticatedPessoasIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cursos/': {
      id: '/_authenticated/admin/cursos/'
      path: '/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AuthenticatedAdminCursosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cursos/$id': {
      id: '/_authenticated/admin/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/admin/cursos/$id'
      preLoaderRoute: typeof AuthenticatedAdminCursosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAlunosRoute: typeof AuthenticatedAdminAlunosRoute
  AuthenticatedAdminComunidadeRoute: typeof AuthenticatedAdminComunidadeRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEncontrosRoute: typeof AuthenticatedAdminEncontrosRoute
  AuthenticatedAdminGestoresRoute: typeof AuthenticatedAdminGestoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCursosIdRoute: typeof AuthenticatedAdminCursosIdRoute
  AuthenticatedAdminCursosIndexRoute: typeof AuthenticatedAdminCursosIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAlunosRoute: AuthenticatedAdminAlunosRoute,
    AuthenticatedAdminComunidadeRoute: AuthenticatedAdminComunidadeRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminEncontrosRoute: AuthenticatedAdminEncontrosRoute,
    AuthenticatedAdminGestoresRoute: AuthenticatedAdminGestoresRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCursosIdRoute: AuthenticatedAdminCursosIdRoute,
    AuthenticatedAdminCursosIndexRoute: AuthenticatedAdminCursosIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBoasVindasRoute: typeof AuthenticatedBoasVindasRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMeusCursosRoute: typeof AuthenticatedMeusCursosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedAulaLessonIdRoute: typeof AuthenticatedAulaLessonIdRoute
  AuthenticatedComunidadePostIdRoute: typeof AuthenticatedComunidadePostIdRoute
  AuthenticatedCursoSlugRoute: typeof AuthenticatedCursoSlugRoute
  AuthenticatedEncontrosIdRoute: typeof AuthenticatedEncontrosIdRoute
  AuthenticatedGestoresIdRoute: typeof AuthenticatedGestoresIdRoute
  AuthenticatedMensagensIdRoute: typeof AuthenticatedMensagensIdRoute
  AuthenticatedPessoasIdRoute: typeof AuthenticatedPessoasIdRoute
  AuthenticatedComunidadeIndexRoute: typeof AuthenticatedComunidadeIndexRoute
  AuthenticatedEncontrosIndexRoute: typeof AuthenticatedEncontrosIndexRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
  AuthenticatedPessoasIndexRoute: typeof AuthenticatedPessoasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBoasVindasRoute: AuthenticatedBoasVindasRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMeusCursosRoute: AuthenticatedMeusCursosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedAulaLessonIdRoute: AuthenticatedAulaLessonIdRoute,
  AuthenticatedComunidadePostIdRoute: AuthenticatedComunidadePostIdRoute,
  AuthenticatedCursoSlugRoute: AuthenticatedCursoSlugRoute,
  AuthenticatedEncontrosIdRoute: AuthenticatedEncontrosIdRoute,
  AuthenticatedGestoresIdRoute: AuthenticatedGestoresIdRoute,
  AuthenticatedMensagensIdRoute: AuthenticatedMensagensIdRoute,
  AuthenticatedPessoasIdRoute: AuthenticatedPessoasIdRoute,
  AuthenticatedComunidadeIndexRoute: AuthenticatedComunidadeIndexRoute,
  AuthenticatedEncontrosIndexRoute: AuthenticatedEncontrosIndexRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  AuthenticatedPessoasIndexRoute: AuthenticatedPessoasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConhecaAComunidadeRoute: ConhecaAComunidadeRoute,
  ConhecaOsEncontrosRoute: ConhecaOsEncontrosRoute,
  DiretrizesRoute: DiretrizesRoute,
  OportunidadesRoute: OportunidadesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TrilhasRoute: TrilhasRoute,
  CursosSlugRoute: CursosSlugRoute,
  GestorSlugRoute: GestorSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
  GestoresIndexRoute: GestoresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
